config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "lists", to: "lists#lists", as: :lists_index
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "lists#index"
  resources :movies
  resources :lists, except: [:edit, :update] do
   resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  # validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  validates :description, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks

# --------------------------PGSearch-------------------------------------

  include PgSearch::Model
  pg_search_scope :search_by_title,
  against: [ :title ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

# ------------------------------------------------------------------------------
  # validates :title, presence: true, uniqueness: true
  # validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    # raise
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @bookmarks =  @list.bookmarks
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    # raise
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @movies = Movie.order("RANDOM()").limit(20)
    @movies = @movies.search_by_title(params[:query]) if params[:query].present?
  end

  def lists
    @lists = List.all
  end

  def show
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
    # @movies = @list.movies
  end

  def new
    @lists = List.all
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_index_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end


  def list_params
    params.require(:list).permit(:name, :description, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    @movie = Movie.find(params[:id])
    @bookmark = Bookmark.new
    @list = List.new
  end

  def update
    @movie = Movie.find(params[:id])
    @count = params[:movie][:list_ids].count - 1
    params[:movie][:list_ids].each do |id|
      next if id == ""
      @bookmark = Bookmark.new
      @list = List.find(id)
      if Bookmark.find_by(list_id: id, movie_id: @movie.id)
        @coiso = Bookmark.find_by(list_id: id, movie_id: @movie.id)
        # raise
        Bookmark.destroy(@coiso.id)
      end
      @bookmark.list = @list
      @bookmark.movie = @movie
      # raise


      # raise
      @count -=  1
      if @bookmark.save! && @count == 0
        redirect_to lists_path
      else
        if @count == 0
          render :show, status: :unprocessable_entity
        end
      end

      # raise
    end
    # redirect_to lists_path
  end
end

  # @list = List.find(params[:movie][:list_ids].last)

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.submit "Submit Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CineBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      body {
        background-color: #161616;
        color: #EEEEEE;
      }
    </style>
  </head>

  <body>
    <div class="navbar d-flex justify-content-between align-items-center px-3">
      <div class="navbar-brand d-flex align-items-center">
        <%= link_to root_path do %>
          <img class="popcorn" src="<%= asset_path('poppcorn.png') %>" alt="Popcorn" style="height:75px;" />
        <% end %>
      </div>
      <div class="d-flex align-items-center">
        <%= link_to lists_index_path, class: "button-85" do %>
          <i class="fa-solid fa-film"></i>
        <% end %>
      </div>
    </div>
  <%= yield %>
  </body>
</html>

app/views/lists/_lists.html.erb
<div class="list-container">
  <div class="list-grid">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <% if list.photo.attached? %>
          <div class="list-item">
            <div class="flip-card">
              <div class="flip-card-inner">
                <!-- Front of the card -->
                <div class="flip-card-front" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.photo.key) %>')">
                </div>
                <!-- Back of the card -->
                <div class="flip-card-back">
                  <h3><%= list.name %></h3>
                  <p><%= list.description %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/_search_bar.html.erb
<div class="search-bar-container">
  <div class="row justify-content-center" data-controller="stop-refresh">
    <div class="col-sm-8 my-3">
      <%= form_with url: root_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search Movies!"
          %>

          <%= button_tag type: "submit", class: "btn d-flex align-items-center" do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="banner">
  <h1>CineBox </h1>
</div>

<%= render "search_bar" %>

<div class="movie-list">
  <% @movies.each do |movie| %>
    <%= link_to movie_path(movie), class: "movie-card" do %>
      <% if movie.poster_url.present? %>
        <%= image_tag(movie.poster_url, alt: movie.title, style: "width: 150px; height: 200px; border-radius: 4px;") %>
      <% end %>
      <div class="movie-info">
        <h2><%= movie.title %></h2>
        <p><%= truncate(movie.overview, length: 60) %></p>
        <p>Rating : <%= movie.rating.to_i %>/10</p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/lists.html.erb
<div class="list-container">
  <div class="list-grid">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <% if list.photo.attached? %>
          <div class="list-item">
            <div class="flip-card">
              <div class="flip-card-inner">
                <!-- Front of the card -->
                <div class="flip-card-front" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(list.photo.key) %>')">
                </div>
                <!-- Back of the card -->
                <div class="flip-card-back">
                  <h3><%= list.name %></h3>
                  <p><%= list.description %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <%= link_to new_list_path, class: "button-85" do %>
    <i class="fa-solid fa-plus"></i>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="new-list-form-container">
  <div class="list-head">
    <h1>Create a new List</h1>
  </div>
  <div class="new-list-form" data-controller="toggle">
    <%= simple_form_for @list, html: {id:"new_list_form"} do |f| %>
      <%= f.input :name,
      wrapper_html: { class: "floating-label" },
      required: false,
      input_html: { data: { action: "blur->toggle#blurName focus->toggle#transitionName",
                            toggle_target: "inputName" }},
      label_html: { data: { toggle_target: "labelName" }}
       %>
      <%= f.input :description,
      as: :text,
      wrapper_html: { class: "floating-label" },
      input_html: { data: { action: "blur->toggle#blurDescription focus->toggle#transitionDescription",
                            toggle_target: "inputDescription" }},
      label_html: { data: { toggle_target: "labelDescription" }},
      required: false %>
      <%= f.input :photo, as: :file %>
    <% end %>
     <button type="submit" class="button-85" form="new_list_form">Create List</button>
  </div>
</div>
<%= render "lists" %>

app/views/lists/show.html.erb
<div class="movie-name">
  <h2><%= @list.name %></h2>
  <p><%= link_to list_path(@list),
                  data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete the list and associated bookmarks?"
                  } do %>
                    <i class="fa-solid fa-trash"></i>
                  <% end %>
  </p>
</div>

<ul>
  <% @list.bookmarks.each do |bookmark| %>
  <% end %>
</ul>

<div class="featured-movies">
  <div class="movies-carousel">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="movies-slide">
        <%= link_to movie_path(bookmark.movie) do %>
          <%= image_tag(bookmark.movie.poster_url, alt: bookmark.movie.title, style: "width: 150px; height: 200px; border-radius: 32px; margin-left: 8px;") %>
        <% end %>
        <div class="movie-infos">
          <ul>
            <li class="movie-title"><strong><%= bookmark.movie.title %></strong></li>
            <div data-controller="read-more" data-read-more-more-text-value="Read more" data-read-more-less-text-value="Read less">
              <li class="my-content" data-read-more-target="content">
                <%= bookmark.movie.overview %>
              </li>
              <button class="read-more-button" data-action="read-more#toggle">Read more</button>
            </div>
            <li><%= bookmark.movie.rating.to_i %> ⭐</li>
            <li>
              <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                <i class="fa-solid fa-trash"></i>
               <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="movie-container">
  <div class="movie-image">
    <% if @movie.poster_url.present? %>
      <%= image_tag(@movie.poster_url, alt: @movie.title) %>
    <% end %>
  </div>

  <div class="movie-info">
    <div>
      <h1><%= @movie.title %></h1>
      <div class="movie-rating">
      <p><%= @movie.rating.to_i %> / 10</p>
        <% @movie.rating.to_i.times do %>
          <i class="fa-solid fa-star fa-rotate-90" style="color: #FFD43B;"></i>
        <% end %>
      </div>
    </div>
    <p><%= @movie.overview %></p>
  </div>
</div>

<div class="add-list-form" data-controller="toggle">
  <button class="button-85" data-action="click->toggle#fire">
    <p>Add to a List</p>
  </button>
  <div class="d-none" data-toggle-target="form">
    <%= simple_form_for(@movie, html: { novalidate: true, class: "no-validation" }) do |f| %>
      <%= f.association :lists, as: :check_boxes %>
      <%= f.submit "Submit Bookmark", class: "button-85" %>
    <% end %>
  </div>
</div>